apiVersion: v1
kind: Pod
metadata:
  name: iperf3-client
spec:
  containers:
    - name: iperf3
      image: networkstatic/iperf3
      command: ["sleep", "infinity"] # Keep the pod running to execute commands manually or via script
