apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iperf3-server
  labels:
    app: iperf3
spec:
  selector:
    matchLabels:
      app: iperf3
  template:
    metadata:
      labels:
        app: iperf3
    spec:
      containers:
        - name: iperf3
          image: networkstatic/iperf3
          args: ["-s"] # Run in server mode
          ports:
            - containerPort: 5201
      nodeSelector:
        kubernetes.io/role: worker # Optional: Ensure only worker nodes are used

